[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"


[[redirects]]
  from = "/send"
  to = "/.netlify/functions/send-email"
  status = 200
  method = "POST"
